# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(verbose_name='currency date')),
                ('base', models.CharField(max_length=3, verbose_name='currency base')),
                ('symbol_target', models.CharField(max_length=3, verbose_name='currency target')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='currency value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
